### ISSUE TITLE
3.1.1 argument named "address_prefixes" is not expected here

### ISSUE THREAD

**Issue by ilyamazya** [Azure/terraform-azurerm-network#41]
Getting error when using **3.1.1** as follows:

**on ".terraform\modules\network-module\terraform-azurerm-network-3.1.1\main.tf line 19, in resource "azurerm_subnet" "subnet":
  19:   address_prefixes     = [var.subnet_prefixes[count.index]]

An argument named "address_prefixes" is not expected here. Did you mean
"address_prefix"?**

When I rolled back to **3.0.1** version - things are working fine.

**Comment by yupwei68** [comment]
Hi @ilyamazya , thanks for opening this issue. Because `address_prefix` currently has been deprecated, referring to https://www.terraform.io/docs/providers/azurerm/r/subnet.html#address_prefix. To fit the latest azurerm, we replace `address_prefix` with `address_prefixes`. Please updating azurerm version or just keep module version as 3.0.1 will be fine
